name: Get Deployment Info
description: Get deployment info from Astronomer API
inputs:
  deployment_id:
    description: The deployment ID
    required: true
  organization_id:
    description: The organization ID
    required: true
  astro_api_token:
    description: The Astronomer API token
    required: true
  astronomer_host:
    description: The Astronomer host
    required: true
  expected_status_code:
    description: The expected status code
    default: 200

outputs:
  desired_dag_tarball_version:
    description: The desired DAG tarball version
    value: ${{ steps.get-deployment-info.outputs.desired_dag_tarball_version }}
  desired_image_version:
    description: The image version
    value: ${{ steps.get-deployment-info.outputs.desired_image_version }}
  hibernation_spec:
    description: The hibernation spec
    value: ${{ steps.get-deployment-info.outputs.hibernation_spec }}

runs:
  using: "composite"
  steps:
    - name: Get Deployment Info
      id: get-deployment-info
      shell: bash
      run: |
        STATUS_CODE=$(curl -s -w "%{http_code}" -o response.json -H "Authorization: Bearer ${{ inputs.astro_api_token }}" "https://api.${{ inputs.astronomer_host }}/v1alpha1/organizations/${{ inputs.organization_id }}/deployments/${{ inputs.deployment_id }}")
        if [[ $STATUS_CODE -ne ${{ inputs.expected_status_code }} ]]; then
          echo "Failed to get expected status code from GET Deployment API. Status code: $STATUS_CODE"
          exit 1
        fi
        desired_dag_tarball_version=$(cat response.json | jq -r '.desiredDagTarballVersion')
        desired_image_version=$(cat response.json | jq -r '.desiredImageVersion')
        hibernation_spec=$(cat response.json | jq -rc '.scalingSpec.hibernationSpec')
        echo "desired_dag_tarball_version=$desired_dag_tarball_version" >> $GITHUB_OUTPUT
        echo "desired_image_version=$desired_image_version" >> $GITHUB_OUTPUT
        echo "hibernation_spec=$hibernation_spec" >> $GITHUB_OUTPUT
